stages:
  - build
  - test
  - deploy

variables:
  GO111MODULE: "on"
  DOCKER_IMAGE_NAME: "olooeez/$CI_PROJECT_NAME"
  DOCKER_IMAGE_TAG: "$CI_COMMIT_TAG"

before_script:
  - go install github.com/swaggo/swag/cmd/swag@latest
  - swag init
  - go mod tidy

build:
  stage: build
  script:
    - go build
  tags:
    - golang
  only:
    - main

test:
  stage: test
  script:
    - go test -v ./...
  tags:
    - golang
  only:
    - merge_requests
    - main

deploy:
  stage: deploy
  only:
    - tags
  script:
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
    - docker build -t "$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG" .
    - docker push "$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG"
    - docker tag "$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG" "$DOCKER_IMAGE_NAME:latest"
    - docker push "$DOCKER_IMAGE_NAME:latest"
  tags:
    - docker
