stages:
  - build
  - test

variables:
  GO111MODULE: "on"

before_script:
  - go install github.com/swaggo/swag/cmd/swag@latest
  - swag init
  - go mod tidy

build:
  stage: build
  script:
    - go build
  tags:
    - golang
  only:
    - main

test:
  stage: test
  script:
    - go test -v ./...
  tags:
    - golang
  only:
    - merge_requests
    - main
